apiVersion: v1
kind: Secret
metadata:
  name: workshop-postgres-superuser
type: Opaque
stringData:
  username: postgres
  password: postgrespassword
---
apiVersion: v1
kind: Secret
metadata:
  name: workshop-postgres-app-user
type: Opaque
stringData:
  username: app
  password: apppassword

