apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cnpg-parent-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: workshop-dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: child-apps
    repoURL: 'https://github.com/tomazb/postgres-cloudnativepg-gitops'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
