apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: workshop-postgres
spec:
  instances: 1
  resources:
    requests:
      memory: "1024Mi"
      cpu: "2"
    limits:
      memory: "8192Mi"
      cpu: "6"

