apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: workshop-postgres
spec:
  instances: 3
  storage:
    size: 20Gi
  resources:
    requests:
      memory: "2Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "6"

