---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cnpg-app
  namespace: openshift-gitops
  annotations:
    # Assign to Wave 1 - deploy this second, only after Wave 0 is Healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: workshop-dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cloudnative-pg/overlays/dev
    repoURL: 'https://github.com/tomazb/postgres-cloudnativepg-gitops'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
